# Generated by Django 5.1.7 on 2025-04-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="photo/avatars/", verbose_name="Аватар"
            ),
        ),
    ]
