# Generated by Django 5.1.7 on 2025-04-02 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="finish_send_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 3, 16, 10, 29, 74688),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_send_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 2, 16, 10, 29, 73689),
                verbose_name="Дата и время первой отправки",
            ),
        ),
    ]
