# Generated by Django 5.1.7 on 2025-04-11 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailing_finish_send_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="finish_send_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 12, 18, 20, 36, 696185),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_send_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 11, 18, 20, 36, 696185),
                verbose_name="Дата и время первой отправки",
            ),
        ),
    ]
