# Generated by Django 5.1.7 on 2025-04-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_remove_receivemail_is_active_alter_mailing_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptmailing",
            name="status",
            field=models.CharField(
                choices=[("ok", "Успешно отправлено"), ("nok", "Ошибка отправки")],
                max_length=3,
            ),
        ),
    ]
