# Generated by Django 5.1.7 on 2025-04-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_attemptsending"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AttemptSending",
        ),
    ]
