# Generated by Django 5.1.7 on 2025-04-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_delete_attemptsending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptmailing",
            name="status",
            field=models.CharField(
                choices=[("ok", "Успешно отправлено"), ("nok", "Ошибка отправки")],
                max_length=50,
            ),
        ),
    ]
