# Generated by Django 5.1.7 on 2025-04-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_alter_attemptmailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptmailing",
            name="date_attempt",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время попытки"
            ),
        ),
    ]
